flatpak:
    image: fedora:latest
    stage: build
    script:
        - dnf -y update && dnf install -y flatpak-builder ostree fuse elfutils dconf git && dnf clean all
        - flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        - flatpak install -y flathub org.kde.Platform//5.11 org.kde.Sdk//5.11
        - flatpak-builder --repo=repo build-dir --force-clean flatpak/net.meijn.onvifviewer.json
        - flatpak build-bundle repo onvifviewer.flatpak net.meijn.onvifviewer
    artifacts:
        paths:
            - onvifviewer.flatpak
    cache:
        paths:
            - .flatpak-builder/cache

test-metadata:
    image: fedora:latest
    stage: test
    script:
        - dnf -y update && dnf install -y libappstream-glib desktop-file-utils && dnf clean all
        - appstream-util validate-strict desktop/net.meijn.onvifviewer.appdata.xml
        - desktop-file-validate --warn-kde desktop/net.meijn.onvifviewer.desktop
