flatpak:
    image: registry.gitlab.com/caspermeijn/docker-images/flatpak-kde:latest
    stage: build
    script:
        - flatpak-builder --repo=repo build-dir --force-clean flatpak/net.meijn.onvifviewer.json
        - flatpak build-bundle repo onvifviewer.flatpak net.meijn.onvifviewer
    artifacts:
        paths:
            - onvifviewer.flatpak
    cache:
        paths:
            - .flatpak-builder/cache

test-metadata:
    image: registry.gitlab.com/caspermeijn/docker-images/appstream:latest
    stage: test
    script:
        - appstream-util validate-strict desktop/net.meijn.onvifviewer.appdata.xml
        - desktop-file-validate --warn-kde desktop/net.meijn.onvifviewer.desktop
