flatpak:
    image: registry.gitlab.com/caspermeijn/docker-images/flatpak-kde:latest
    stage: build
    script:
        - flatpak-builder --repo=repo build-dir --keep-build-dirs flatpak/net.meijn.onvifviewer.json
        - flatpak build-bundle repo onvifviewer.flatpak net.meijn.onvifviewer
        - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --run build-dir flatpak/net.meijn.onvifviewer.json ninja -C .flatpak-builder/build/onvifviewer test
    artifacts:
        paths:
            - onvifviewer.flatpak
    cache:
        paths:
            - .flatpak-builder/cache

test-metadata:
    image: registry.gitlab.com/caspermeijn/docker-images/appstream:latest
    stage: test
    script:
        - appstream-util validate-strict desktop/net.meijn.onvifviewer.appdata.xml
        - desktop-file-validate --warn-kde desktop/net.meijn.onvifviewer.desktop

sast:
    image: docker:stable
    stage: test
    variables:
        DOCKER_DRIVER: overlay2
    allow_failure: true
    services:
        - docker:stable-dind
    script:
        - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
        - docker run 
            --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
            --volume "$PWD:/code"
            --volume /var/run/docker.sock:/var/run/docker.sock
            "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
    artifacts:
        paths: [gl-sast-report.json]
