lane :upload_alpha do
  sh("./prepare_metadata_for_alpha.py", "--manifest=AndroidManifest-arm.xml", "--fastlane=metadata")
  sh("./prepare_metadata_for_alpha.py", "--manifest=AndroidManifest-aarch64.xml", "--fastlane=metadata")
  upload_to_play_store(track: 'alpha', apk_paths: [ ENV["APK_ARM_PATH"], ENV["APK_AARCH64_PATH"] ], check_superseded_tracks: true)
end
